version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_TCP_PORT: 3307
    ports:
    - 3307:3307
    expose:
      - 3307

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_PORT: 3307
      PMA_HOST: db
    ports:
      - 5050:80
    restart: always

volumes:
  db_data: {}